#!/bin/bash
echo ''' #!/bin/bash
 bash file
 git add .
 git commit -m .
 git config pull.rebase true
 git pull
 php -S 127.0.0.1:8000
 echo its that easy
 echo you see it works
 echo "\n \n \n is this not easier \n \n \n " ''' > fast
